droidconKE/droidconKE2022Android

- README.md
- contributing.md
This PR adds the contribution guideliness.
> Setup contribution guideliness

- README.md
Adds link to mock-ups to readme
> Update readme to include designs.

- contributing.md
Adds ticket contribution guideliness.
> Feature: Add Ticket contribution guidelines

- gradle/libs.versions.toml
- presentation/build.gradle.kts
Fixing Gradle error brought by adding splashscreen api dependency
None
> fixing gradle errors

- .github/workflows/contributors.yml
- CONTRIBUTING.md
- README.md
> Add contributors on README.md

- data/src/main/java/com/android254/data/di/NetworkModule.kt
- data/src/main/java/com/android254/data/network/util/HttpClientFactory.kt
- data/src/main/java/com/android254/data/network/util/TokenProvider.kt
- data/src/test/java/com/android254/data/dao/network/AuthApiTest.kt
> feat: Add TokenProvider interface

- gradle/libs.versions.toml
- presentation/build.gradle.kts
- presentation/src/main/java/com/android254/presentation/login/view/LoginScreen.kt
- presentation/src/test/java/com/android254/presentation/login/view/LoginScreenTest.kt
_This PR refactors the Login screen to only allow Google login._ please check the below boxes
by others._
> refactor: Remove other login fields

- presentation/src/main/java/com/android254/presentation/auth/view/LoginScreen.kt
- presentation/src/main/java/com/android254/presentation/auth/view/SignUpScreen.kt
- presentation/src/main/java/com/android254/presentation/common/navigation/Navigation.kt
- presentation/src/main/java/com/android254/presentation/common/navigation/Screens.kt
- presentation/src/main/res/drawable/toolbar_bg_sign_up_dark.xml
- presentation/src/main/res/drawable/topbar_bg_sign_up.xml
- presentation/src/main/res/values/colors.xml
- presentation/src/main/res/values/strings.xml
and check that you understand and have followed it as best as possible 
Changes
- Implemented an empty sign up screen.
- Implemented navigation to and from the login screen. 
- Made sign up and login screens scrollable
_ please check the below boxes
- [ x ] I have followed the coding conventions
- [ x ] I have tested the changes added on a physical device
by others._
> Implement empty sign up screen

- build.gradle.kts
Updating AGP version to the latest
by others._
> Update AGP Version

- chai/src/main/java/com/droidconke/chai/atoms/Color.kt
this introdcuces the colours to Chai by explicitly nnmaing them. to use them we can now call colours but under the material theme, Future thenme fix is coming with additions to the type
N/A
N.A
N/A
> Chai colours

- README.md
- gradle/libs.versions.toml
Adding Documentation For Versions Catalog and giving context as to why we chose versions catalog and how to add dependencies on the project
by others._
> Versions Catalog Documentation

- data/build.gradle.kts
- data/src/main/java/com/android254/data/di/RepoModule.kt
- data/src/main/java/com/android254/data/repos/AuthManager.kt
- data/src/test/java/com/android254/data/repos/AuthManagerTest.kt
- domain/src/main/java/com/android254/domain/models/DataResult.kt
- domain/src/main/java/com/android254/domain/repos/AuthRepo.kt
- gradle/libs.versions.toml
- presentation/src/test/java/com/android254/presentation/login/view/LoginScreenTest.kt
Adds the AuthRepo interface and its implementation
by others._
> feat: Add AuthRepo and its implemenation

- presentation/src/main/java/com/android254/presentation/common/bottomnav/BottomNavigationBar.kt
- presentation/src/main/java/com/android254/presentation/common/navigation/Navigation.kt
- presentation/src/main/java/com/android254/presentation/feedback/view/FeedBackScreen.kt
- presentation/src/main/res/values/strings.xml
- presentation/src/test/java/com/android254/presentation/feedback/view/FeedBackScreenTest.kt
This PR improves the navigation flow by:
- Making the Home Screen the default navigation destination
- Adds `popUpTo` when navigating the screens on the bottom bar
---
by others._
> refactor: Corrects navigation flow

- README.md
> Remove usecases

- data/src/main/java/com/android254/data/network/util/SafeApiCall.kt
> Add dataResultSafeApiCall

- presentation/build.gradle.kts
- presentation/src/main/java/com/android254/presentation/common/components/DroidconAppBar.kt
- presentation/src/main/res/drawable/smile.xml
- presentation/src/main/res/drawable/whilte_padlock.xml
- presentation/src/main/res/values/strings.xml
Enhances the DroidconAppBar composable to add click handlers i.e feedback/login/logout actions. 
by others._
> feat: Enhance the DroidconAppBar

- data/.gitignore
- presentation/src/main/java/com/android254/presentation/common/navigation/Navigation.kt
- presentation/src/main/java/com/android254/presentation/common/navigation/Screens.kt
- presentation/src/main/java/com/android254/presentation/models/Speaker.kt
- presentation/src/main/java/com/android254/presentation/speakers/SpeakersViewModel.kt
- presentation/src/main/java/com/android254/presentation/speakers/view/SpeakerComponent.kt
- presentation/src/main/java/com/android254/presentation/speakers/view/SpeakersScreen.kt
- presentation/src/main/res/values/colors.xml
- presentation/src/main/res/values/strings.xml
- presentation/src/test/java/com/android254/presentation/speakers/view/SpeakersScreenTest.kt
and check that you understand and have followed it as best as possible 
Explain what your feature does in a short paragraph.
- Implemented speakers screen
_ please check the below boxes
by others._
Screenshots
> Implement speakers screen

- app/src/main/AndroidManifest.xml
- build.gradle.kts
- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/com/android254/presentation/activity/MainActivity.kt
> Update Dependencies and merge manifest

- .github/workflows/branch.yml
> Modify CI: add on pull_request

- .github/workflows/branch.yml
- .github/workflows/main.yml
- .gitignore
- README.md
- app/google-services.json
> Add google-services json

- presentation/src/main/java/com/android254/presentation/common/navigation/Navigation.kt
- presentation/src/main/java/com/android254/presentation/home/components/HomeBannerSection.kt
- presentation/src/main/java/com/android254/presentation/home/components/HomeSpacer.kt
- presentation/src/main/java/com/android254/presentation/home/components/HomeSpeakerComponent.kt
- presentation/src/main/java/com/android254/presentation/home/components/HomeSpeakersSection.kt
- presentation/src/main/java/com/android254/presentation/home/screen/HomeScreen.kt
- presentation/src/main/java/com/android254/presentation/home/viewmodel/HomeViewModel.kt
- presentation/src/main/java/com/android254/presentation/home/viewstate/HomeViewState.kt
- presentation/src/main/java/com/android254/presentation/speakers/SpeakersViewModel.kt
- presentation/src/main/java/com/android254/presentation/speakers/view/SpeakersScreen.kt
- presentation/src/main/res/values/colors.xml
- presentation/src/main/res/values/strings.xml
- presentation/src/test/java/com/android254/presentation/home/components/HomeBannerSectionTest.kt
- presentation/src/test/java/com/android254/presentation/home/screen/HomeScreenTest.kt
and check that you understand and have followed it as best as possible,
Explain what your feature does in a short paragraph.
Implemented the speakers' section on the home screen. 
_ please check the below boxes
by others._
> Implement home speakers section

- data/src/main/java/com/android254/data/network/Constants.kt
- data/src/main/java/com/android254/data/network/apis/FeedbackApi.kt
- data/src/main/java/com/android254/data/network/models/Session.kt
- data/src/main/java/com/android254/data/network/models/SessionDataModel.kt
- data/src/main/java/com/android254/data/network/models/payloads/Feedback.kt
- data/src/main/java/com/android254/data/network/util/SafeApiCall.kt
- data/src/test/java/com/android254/data/network/FeedbackApiTest.kt
Add feedback endpoint client.
(I have also edited `dataResultSafeApiCall`'s interface a bit)
by others._
I have tested that the api client code works as expected.
The change to `dataResultSafeApiCall`'s interface may affect other things that use it but it had not been used yet in the main branch or the open PRs
> [Data] Send feedback to API

- presentation/src/main/java/com/android254/presentation/common/components/SponsorsCard.kt
- presentation/src/main/java/com/android254/presentation/home/screen/HomeScreen.kt
- presentation/src/main/res/values/strings.xml
- presentation/src/test/java/com/android254/presentation/home/screen/HomeScreenTest.kt
This PR adds the Sponsors section in the home Screen
by others._
> Add Sponsors in Home screen

- .github/workflows/branch.yml
- data/src/main/java/com/android254/data/network/Constants.kt
- data/src/main/java/com/android254/data/network/apis/SessionRemoteSource.kt
- data/src/main/java/com/android254/data/network/models/responses/PaginationMetaData.kt
- data/src/main/java/com/android254/data/repos/SessionsManager.kt
- data/src/test/java/com/android254/data/network/SessionApiTest.kt
- data/src/test/java/com/android254/data/repos/SampleData.kt
- data/src/test/java/com/android254/data/repos/SessionsManagerTest.kt
- domain/src/main/java/com/android254/domain/models/ResourceResult.kt
- fastlane/Fastfile
- presentation/src/main/java/com/android254/presentation/common/navigation/Navigation.kt
- presentation/src/main/java/com/android254/presentation/common/navigation/Screens.kt
- presentation/src/main/java/com/android254/presentation/home/components/HomeSpeakerComponent.kt
- presentation/src/main/java/com/android254/presentation/home/components/HomeSpeakersSection.kt
- presentation/src/main/java/com/android254/presentation/home/screen/HomeScreen.kt
- presentation/src/main/java/com/android254/presentation/models/Speaker.kt
- presentation/src/main/java/com/android254/presentation/sessions/view/SessionsViewModel.kt
- presentation/src/main/java/com/android254/presentation/speakers/SpeakersViewModel.kt
- presentation/src/main/java/com/android254/presentation/speakers/view/SpeakerComponent.kt
- presentation/src/main/java/com/android254/presentation/speakers/view/SpeakerDetailsScreen.kt
- presentation/src/main/java/com/android254/presentation/speakers/view/SpeakersScreen.kt
- presentation/src/main/java/com/android254/presentation/speakers/view/TopAppBar.kt
- presentation/src/main/res/drawable/topbar_speaker_bg.xml
- presentation/src/main/res/values/strings.xml
- presentation/src/test/java/com/android254/presentation/feedback/view/FeedBackScreenTest.kt
- presentation/src/test/java/com/android254/presentation/speakers/view/SpeakerDetailsScreenTest.kt
- Adds speaker details screen skeleton
- Fixes broken tests
- Updates Github actions to include unit tests
by others._
> feat: Add speaker details and cleanup tests

- presentation/src/main/java/com/android254/presentation/common/bottomnav/BottomNavigationBar.kt
- presentation/src/main/java/com/android254/presentation/common/theme/Color.kt
> bottomNavColors

- data/src/main/java/com/android254/data/dao/SpeakerDao.kt
- data/src/main/java/com/android254/data/network/models/responses/SpeakerDTO.kt
- data/src/main/java/com/android254/data/repos/SpeakersManager.kt
- data/src/main/java/com/android254/data/repos/mappers/SpeakerMapper.kt
- data/src/test/java/com/android254/data/network/SpeakerRemoteSourceTest.kt
- domain/src/main/java/com/android254/domain/models/Speaker.kt
- domain/src/main/java/com/android254/domain/repos/SpeakersRepo.kt
- presentation/src/main/java/com/android254/presentation/common/bottomnav/BottomNavigationBar.kt
- presentation/src/main/java/com/android254/presentation/common/navigation/Navigation.kt
- presentation/src/main/java/com/android254/presentation/common/navigation/Screens.kt
- presentation/src/main/java/com/android254/presentation/models/SpeakerUI.kt
- presentation/src/main/java/com/android254/presentation/speakers/SpeakersViewModel.kt
- presentation/src/main/java/com/android254/presentation/speakers/view/SpeakerComponent.kt
- presentation/src/main/java/com/android254/presentation/speakers/view/SpeakerDetailsScreen.kt
- presentation/src/main/java/com/android254/presentation/speakers/view/SpeakersScreen.kt
- presentation/src/test/java/com/android254/presentation/speakers/view/SpeakerDetailsScreenTest.kt
- presentation/src/test/java/com/android254/presentation/speakers/view/SpeakersScreenTest.kt
- Finish integrating speaker logic with UI
by others._
> feat: Finalize speaker logic

- .github/workflows/deploy-to-playstore.yml
- data/schemas/com.android254.data.db.Database/1.json
- data/src/main/java/com/android254/data/db/Database.kt
- data/src/main/java/com/android254/data/db/model/OrganizerEntity.kt
- data/src/main/java/com/android254/data/di/RepoModule.kt
- data/src/main/java/com/android254/data/network/models/responses/OrganizerDTO.kt
- data/src/main/java/com/android254/data/network/util/HttpClientFactory.kt
- data/src/main/java/com/android254/data/repos/OrganizersSource.kt
- data/src/main/java/com/android254/data/repos/mappers/OrganizersMapper.kt
- data/src/main/java/com/android254/data/repos/mappers/SpeakerMapper.kt
- data/src/test/java/com/android254/data/network/OrganizersApiTest.kt
- domain/src/main/java/com/android254/domain/models/Organizer.kt
- domain/src/main/java/com/android254/domain/repos/OrganizersRepository.kt
- presentation/src/main/java/com/android254/presentation/about/view/AboutScreen.kt
- presentation/src/main/java/com/android254/presentation/about/view/AboutViewModel.kt
- presentation/src/main/java/com/android254/presentation/speakers/SpeakersViewModel.kt
- presentation/src/test/java/com/android254/presentation/about/view/AboutScreenTest.kt
- presentation/src/test/java/com/android254/presentation/home/components/HomeBannerSectionTest.kt
- whatsnew/whatsnew-en-US
> Fix main branch
